version: '3'

services:
  servidor:
    build:
      context: .
      dockerfile: Dockerfile.servidor
    networks:
      cristian_net:
        ipv4_address: 172.0.0.2
    environment:
      - HOST=0.0.0.0
    command: python servidor_ntp.py
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"


  cliente1:
    build:
      context: .
      dockerfile: Dockerfile.cliente
    networks:
      cristian_net:
        ipv4_address: 172.0.0.3
    depends_on:
      - servidor
    command: python cliente_cristian.py 1
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"


  cliente2:
    build:
      context: .
      dockerfile: Dockerfile.cliente
    networks:
      cristian_net:
        ipv4_address: 172.0.0.4
    depends_on:
      - servidor
    command: python cliente_cristian.py 2
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"


  cliente3:
    build:
      context: .
      dockerfile: Dockerfile.cliente
    networks:
      cristian_net:
        ipv4_address: 172.0.0.5
    depends_on:
      - servidor
    command: python cliente_cristian.py 3
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"


  cliente4:
    build:
      context: .
      dockerfile: Dockerfile.cliente
    networks:
      cristian_net:
        ipv4_address: 172.0.0.6
    depends_on:
      - servidor
    command: python cliente_cristian.py 4
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  cristian_net:
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/16 